### ISSUE TITLE
MongoDB should be local to avoid issues with cloud storage.

### ISSUE THREAD

**Issue by xzzz3** [CS3219-AY2324S1/ay2324s1-course-assessment-g29#23]
**Is your feature request related to a problem? Please describe.**
Cloud storage may cause issues like compatibility problems on different networks and slow response time.

**Describe the solution you'd like**
Shift MongoDB to be stored locally.

**Describe alternatives you've considered**
The alternative to this is to remain it online and troubleshoot the compatibility issue, which would be overly troublesome.

**Comment by benedictchuajj** [comment]
Optional
